// Code generated by github.com/eqld/optional/cmd, DO NOT EDIT
package optional

import "encoding/json"

// Int64 is a superset of type int64 that has explicit "empty" value.
type Int64 struct {
	Value   int64
	Present bool
}

// MakeInt64 converts int64 to Int64
func MakeInt64(value int64) Int64 {
	return Int64{Value: value, Present: true}
}

// MarshalJSON marshals Int64 to json
func (o Int64) MarshalJSON() ([]byte, error) {
	if !o.Present {
		return []byte("null"), nil
	}

	return json.Marshal(o.Value)
}

// UnmarshalJSON unmarshals Int64 from json
func (o *Int64) UnmarshalJSON(data []byte) error {
	if len(data) == 4 && string(data) == "null" {
		return nil
	}

	o.Present = true

	return json.Unmarshal(data, &o.Value)
}
