// Code generated by github.com/eqld/optional/cmd, DO NOT EDIT
package optional

import "encoding/json"

// Uint32 is a superset of type uint32 that has explicit "empty" value.
type Uint32 struct {
	Value   uint32
	Present bool
}

// MakeUint32 converts uint32 to Uint32
func MakeUint32(value uint32) Uint32 {
	return Uint32{Value: value, Present: true}
}

// MarshalJSON marshals Uint32 to json
func (o Uint32) MarshalJSON() ([]byte, error) {
	if !o.Present {
		return []byte("null"), nil
	}

	return json.Marshal(o.Value)
}

// UnmarshalJSON unmarshals Uint32 from json
func (o *Uint32) UnmarshalJSON(data []byte) error {
	if len(data) == 4 && string(data) == "null" {
		return nil
	}

	o.Present = true

	return json.Unmarshal(data, &o.Value)
}
