package optional

// Code generated by github.com/eqld/optional/cmd, DO NOT EDIT

import (
	"encoding/json"
	"errors"
)

// Float64 is a superset of type float64 that has explicit "empty" value.
type Float64 struct {
	Value   float64
	Present bool
}

// MakeFloat64 converts float64 to Float64.
func MakeFloat64(value float64) Float64 {
	return Float64{Value: value, Present: true}
}

// MakeFloat64FromPtr converts a pointer to float64 to Float64.
func MakeFloat64FromPtr(ptr *float64) Float64 {
	if ptr == nil {
		return Float64{}
	}

	return MakeFloat64(*ptr)
}

// SafeValue safely converts Float64 to float64 returning its default value if the value of Float64 is not present.
func (o Float64) SafeValue() (value float64) {
	if o.Present {
		value = o.Value
	}

	return
}

// SafePtr safely converts Float64 to a pointer to float64 returning nil pointer if the value of Float64 is not present;
// the pointer, if not nil, DOES NOT point to the underlying value of Float64.
func (o Float64) SafePtr() (ptr *float64) {
	if o.Present {
		ptr = new(float64)
		*ptr = o.Value
	}

	return
}

// SafeValueWithFlag safely converts Float64 to float64 returning it with a flag set to true
// or its default value and the flag set to false if the value of Float64 is not present.
func (o Float64) SafeValueWithFlag() (value float64, ok bool) {
	if !o.Present {
		return
	}

	return o.Value, o.Present
}

// SafeValueWithErr safely converts Float64 to float64 returning it with nil error
// or its default value and non-nil error if the value of Float64 is not present.
func (o Float64) SafeValueWithErr() (value float64, err error) {
	if !o.Present {
		err = errors.New("value of optional.Float64 is not present")
		return
	}

	return o.Value, nil
}

// SafePtrWithFlag safely converts Float64 to a pointer to float64 returning a pointer to a value with a flag set to true
// or nil pointer and the flag set to false if the value of Float64 is not present;
// the pointer, if not nil, DOES NOT point to the underlying value of Float64.
func (o Float64) SafePtrWithFlag() (ptr *float64, ok bool) {
	if !o.Present {
		return
	}

	ptr = new(float64)
	*ptr, ok = o.Value, o.Present

	return
}

// SafePtrWithErr safely converts Float64 to a pointer to float64 returning a pointer to a value with nil error
// or nil pointer and non-nil error if the value of Float64 is not present;
// the pointer, if not nil, DOES NOT point to the underlying value of Float64.
func (o Float64) SafePtrWithErr() (ptr *float64, err error) {
	if !o.Present {
		err = errors.New("value of optional.Float64 is not present")
		return
	}

	ptr = new(float64)
	*ptr = o.Value

	return
}

// MarshalJSON marshals Float64 to json.
func (o Float64) MarshalJSON() ([]byte, error) {
	if !o.Present {
		return []byte("null"), nil
	}

	return json.Marshal(o.Value)
}

// UnmarshalJSON unmarshals Float64 from json.
func (o *Float64) UnmarshalJSON(data []byte) error {
	if len(data) == 4 && string(data) == "null" {
		return nil
	}

	o.Present = true

	return json.Unmarshal(data, &o.Value)
}
