// Code generated by github.com/eqld/optional/cmd, DO NOT EDIT
package optional

import "encoding/json"

// Complex64 is a superset of type complex64 that has explicit "empty" value.
type Complex64 struct {
	Value   complex64
	Present bool
}

// MarshalJSON marshalls Complex64 to json
func (o Complex64) MarshalJSON() ([]byte, error) {
	if !o.Present {
		return []byte("null"), nil
	}
	return json.Marshal(o.Value)
}

// UnmarshalJSON unmarshalls Complex64 from json
func (o *Complex64) UnmarshalJSON(data []byte) error {
	if len(data) == 4 && string(data) == "null" {
		return nil
	}

	o.Present = true

	return json.Unmarshal(data, &o.Value)
}
