// Code generated by github.com/eqld/optional/cmd, DO NOT EDIT
package optional

import "encoding/json"

// Uint64 is a superset of type uint64 that has explicit "empty" value.
type Uint64 struct {
	Value   uint64
	Present bool
}

// MarshalJSON marshalls Uint64 to json
func (o Uint64) MarshalJSON() ([]byte, error) {
	if !o.Present {
		return []byte("null"), nil
	}
	return json.Marshal(o.Value)
}

// UnmarshalJSON unmarshalls Uint64 from json
func (o *Uint64) UnmarshalJSON(data []byte) error {
	if len(data) == 4 && string(data) == "null" {
		return nil
	}

	o.Present = true

	return json.Unmarshal(data, &o.Value)
}
