package optional

// Code generated by github.com/eqld/optional/cmd, DO NOT EDIT

import (
	"encoding/json"
	"errors"
)

// Rune is a superset of type rune that has explicit "empty" value.
type Rune struct {
	Value   rune
	Present bool
}

// MakeRune converts rune to Rune.
func MakeRune(value rune) Rune {
	return Rune{Value: value, Present: true}
}

// MakeRuneFromPtr converts a pointer to rune to Rune.
func MakeRuneFromPtr(ptr *rune) Rune {
	if ptr == nil {
		return Rune{}
	}

	return MakeRune(*ptr)
}

// SafeValue safely converts Rune to rune returning its default value if the value of Rune is not present.
func (o Rune) SafeValue() (value rune) {
	if o.Present {
		value = o.Value
	}

	return
}

// SafePtr safely converts Rune to a pointer to rune returning nil pointer if the value of Rune is not present;
// the pointer, if not nil, DOES NOT point to the underlying value of Rune.
func (o Rune) SafePtr() (ptr *rune) {
	if o.Present {
		ptr = new(rune)
		*ptr = o.Value
	}

	return
}

// SafeValueWithFlag safely converts Rune to rune returning it with a flag set to true
// or its default value and the flag set to false if the value of Rune is not present.
func (o Rune) SafeValueWithFlag() (value rune, ok bool) {
	if !o.Present {
		return
	}

	return o.Value, o.Present
}

// SafeValueWithErr safely converts Rune to rune returning it with nil error
// or its default value and non-nil error if the value of Rune is not present.
func (o Rune) SafeValueWithErr() (value rune, err error) {
	if !o.Present {
		err = errors.New("value of optional.Rune is not present")
		return
	}

	return o.Value, nil
}

// SafePtrWithFlag safely converts Rune to a pointer to rune returning a pointer to a value with a flag set to true
// or nil pointer and the flag set to false if the value of Rune is not present;
// the pointer, if not nil, DOES NOT point to the underlying value of Rune.
func (o Rune) SafePtrWithFlag() (ptr *rune, ok bool) {
	if !o.Present {
		return
	}

	ptr = new(rune)
	*ptr, ok = o.Value, o.Present

	return
}

// SafePtrWithErr safely converts Rune to a pointer to rune returning a pointer to a value with nil error
// or nil pointer and non-nil error if the value of Rune is not present;
// the pointer, if not nil, DOES NOT point to the underlying value of Rune.
func (o Rune) SafePtrWithErr() (ptr *rune, err error) {
	if !o.Present {
		err = errors.New("value of optional.Rune is not present")
		return
	}

	ptr = new(rune)
	*ptr = o.Value

	return
}

// MarshalJSON marshals Rune to json.
func (o Rune) MarshalJSON() ([]byte, error) {
	if !o.Present {
		return []byte("null"), nil
	}

	return json.Marshal(o.Value)
}

// UnmarshalJSON unmarshals Rune from json.
func (o *Rune) UnmarshalJSON(data []byte) error {
	if len(data) == 4 && string(data) == "null" {
		return nil
	}

	o.Present = true

	return json.Unmarshal(data, &o.Value)
}
