package optional

// Code generated by github.com/eqld/optional/cmd, DO NOT EDIT

import (
	"encoding/json"
	"errors"
)

// Int64 is a superset of type int64 that has explicit "empty" value.
type Int64 struct {
	Value   int64
	Present bool
}

// MakeInt64 converts int64 to Int64.
func MakeInt64(value int64) Int64 {
	return Int64{Value: value, Present: true}
}

// MakeInt64FromPtr converts a pointer to int64 to Int64.
func MakeInt64FromPtr(ptr *int64) Int64 {
	if ptr == nil {
		return Int64{}
	}

	return MakeInt64(*ptr)
}

// SafeValue safely converts Int64 to int64 returning its default value if the value of Int64 is not present.
func (o Int64) SafeValue() (value int64) {
	if o.Present {
		value = o.Value
	}

	return
}

// SafePtr safely converts Int64 to a pointer to int64 returning nil pointer if the value of Int64 is not present;
// the pointer, if not nil, DOES NOT point to the underlying value of Int64.
func (o Int64) SafePtr() (ptr *int64) {
	if o.Present {
		ptr = new(int64)
		*ptr = o.Value
	}

	return
}

// SafeValueWithFlag safely converts Int64 to int64 returning it with a flag set to true
// or its default value and the flag set to false if the value of Int64 is not present.
func (o Int64) SafeValueWithFlag() (value int64, ok bool) {
	if !o.Present {
		return
	}

	return o.Value, o.Present
}

// SafeValueWithErr safely converts Int64 to int64 returning it with nil error
// or its default value and non-nil error if the value of Int64 is not present.
func (o Int64) SafeValueWithErr() (value int64, err error) {
	if !o.Present {
		err = errors.New("value of optional.Int64 is not present")
		return
	}

	return o.Value, nil
}

// SafePtrWithFlag safely converts Int64 to a pointer to int64 returning a pointer to a value with a flag set to true
// or nil pointer and the flag set to false if the value of Int64 is not present;
// the pointer, if not nil, DOES NOT point to the underlying value of Int64.
func (o Int64) SafePtrWithFlag() (ptr *int64, ok bool) {
	if !o.Present {
		return
	}

	ptr = new(int64)
	*ptr, ok = o.Value, o.Present

	return
}

// SafePtrWithErr safely converts Int64 to a pointer to int64 returning a pointer to a value with nil error
// or nil pointer and non-nil error if the value of Int64 is not present;
// the pointer, if not nil, DOES NOT point to the underlying value of Int64.
func (o Int64) SafePtrWithErr() (ptr *int64, err error) {
	if !o.Present {
		err = errors.New("value of optional.Int64 is not present")
		return
	}

	ptr = new(int64)
	*ptr = o.Value

	return
}

// MarshalJSON marshals Int64 to json.
func (o Int64) MarshalJSON() ([]byte, error) {
	if !o.Present {
		return []byte("null"), nil
	}

	return json.Marshal(o.Value)
}

// UnmarshalJSON unmarshals Int64 from json.
func (o *Int64) UnmarshalJSON(data []byte) error {
	if len(data) == 4 && string(data) == "null" {
		return nil
	}

	o.Present = true

	return json.Unmarshal(data, &o.Value)
}
