// Code generated by github.com/eqld/optional/cmd, DO NOT EDIT
package optional

import "encoding/json"

// Int8 is a superset of type int8 that has explicit "empty" value.
type Int8 struct {
	Value   int8
	Present bool
}

// MakeInt8 converts int8 to Int8
func MakeInt8(value int8) Int8 {
	return Int8{Value: value, Present: true}
}

// MarshalJSON marshals Int8 to json
func (o Int8) MarshalJSON() ([]byte, error) {
	if !o.Present {
		return []byte("null"), nil
	}

	return json.Marshal(o.Value)
}

// UnmarshalJSON unmarshals Int8 from json
func (o *Int8) UnmarshalJSON(data []byte) error {
	if len(data) == 4 && string(data) == "null" {
		return nil
	}

	o.Present = true

	return json.Unmarshal(data, &o.Value)
}
