package optional

// Code generated by github.com/eqld/optional/cmd, DO NOT EDIT

import (
	"encoding/json"
	"errors"
)

// Uint16 is a superset of type uint16 that has explicit "empty" value.
type Uint16 struct {
	Value   uint16
	Present bool
}

// MakeUint16 converts uint16 to Uint16.
func MakeUint16(value uint16) Uint16 {
	return Uint16{Value: value, Present: true}
}

// MakeUint16FromPtr converts a pointer to uint16 to Uint16.
func MakeUint16FromPtr(ptr *uint16) Uint16 {
	if ptr == nil {
		return Uint16{}
	}

	return MakeUint16(*ptr)
}

// SafeValue safely converts Uint16 to uint16 returning its default value if the value of Uint16 is not present.
func (o Uint16) SafeValue() (value uint16) {
	if o.Present {
		value = o.Value
	}

	return
}

// SafePtr safely converts Uint16 to a pointer to uint16 returning nil pointer if the value of Uint16 is not present;
// the pointer, if not nil, DOES NOT point to the underlying value of Uint16.
func (o Uint16) SafePtr() (ptr *uint16) {
	if o.Present {
		ptr = new(uint16)
		*ptr = o.Value
	}

	return
}

// SafeValueWithFlag safely converts Uint16 to uint16 returning it with a flag set to true
// or its default value and the flag set to false if the value of Uint16 is not present.
func (o Uint16) SafeValueWithFlag() (value uint16, ok bool) {
	if !o.Present {
		return
	}

	return o.Value, o.Present
}

// SafeValueWithErr safely converts Uint16 to uint16 returning it with nil error
// or its default value and non-nil error if the value of Uint16 is not present.
func (o Uint16) SafeValueWithErr() (value uint16, err error) {
	if !o.Present {
		err = errors.New("value of optional.Uint16 is not present")
		return
	}

	return o.Value, nil
}

// SafePtrWithFlag safely converts Uint16 to a pointer to uint16 returning a pointer to a value with a flag set to true
// or nil pointer and the flag set to false if the value of Uint16 is not present;
// the pointer, if not nil, DOES NOT point to the underlying value of Uint16.
func (o Uint16) SafePtrWithFlag() (ptr *uint16, ok bool) {
	if !o.Present {
		return
	}

	ptr = new(uint16)
	*ptr, ok = o.Value, o.Present

	return
}

// SafePtrWithErr safely converts Uint16 to a pointer to uint16 returning a pointer to a value with nil error
// or nil pointer and non-nil error if the value of Uint16 is not present;
// the pointer, if not nil, DOES NOT point to the underlying value of Uint16.
func (o Uint16) SafePtrWithErr() (ptr *uint16, err error) {
	if !o.Present {
		err = errors.New("value of optional.Uint16 is not present")
		return
	}

	ptr = new(uint16)
	*ptr = o.Value

	return
}

// Equals returns true if both values are not present or both values are present and are equal according to a provided determinant.
func (o Uint16) Equals(other Uint16, determinant func(this, other uint16) bool) bool {
	return (!o.Present && !other.Present) || (o.Present && other.Present && determinant(o.Value, other.Value))
}

// Compare returns a result of provided comparator and true if both values are present, otherwise it returns 0 and false.
func (o Uint16) Compare(other Uint16, comparator func(this, other uint16) int) (int, bool) {
	if !o.Present || !other.Present {
		return 0, false
	}

	return comparator(o.Value, other.Value), true
}

// Filter returns the Uint16 if its value is present and it matches the given predicate, otherwise it returns an empty Uint16.
func (o Uint16) Filter(test func(value uint16) bool) (result Uint16) {
	if !o.Present || !test(o.Value) {
		return
	}

	return o
}

// Map applies the provided mapping function to a value and returns its result as Uint16 if the value is present,
// otherwise is returns an empty Uint16.
func (o Uint16) Map(mapper func(value uint16) (result uint16, present bool)) (result Uint16) {
	if !o.Present {
		return
	}

	result.Value, result.Present = mapper(o.Value)

	return
}

// IfPresent invokes the specified action with the value if it is present.
func (o Uint16) IfPresent(action func(value uint16)) {
	if o.Present {
		action(o.Value)
	}
}

// OrElse returns the value if it is present, otherwise it returns given other value.
func (o Uint16) OrElse(other uint16) uint16 {
	if !o.Present {
		return other
	}

	return o.Value
}

// OrElseFlag returns the value if it is present with a flag set to true, otherwise it returns given other value
// and the flag set to false.
func (o Uint16) OrElseFlag(other uint16) (uint16, bool) {
	if !o.Present {
		return other, false
	}

	return o.Value, o.Present
}

// OrElseErr returns the value if it is present with nil error, otherwise it returns given other value
// and non-nil error.
func (o Uint16) OrElseErr(other uint16) (uint16, error) {
	if !o.Present {
		return other, errors.New("value of optional.Uint16 is not present")
	}

	return o.Value, nil
}

// OrElseGet returns the value if it is present, otherwise it invokes a supplier and returns a result of that invocation.
func (o Uint16) OrElseGet(supplier func() uint16) uint16 {
	if !o.Present {
		return supplier()
	}

	return o.Value
}

// OrElseGetFlag returns the value if it is present with a flag set to true, otherwise it invokes a supplier and returns
// a result of that invocation with a flag set to false.
func (o Uint16) OrElseGetFlag(supplier func() uint16) (result uint16, ok bool) {
	if !o.Present {
		return supplier(), false
	}

	return o.Value, o.Present
}

// OrElseGetErr returns the value if it is present with nil error, otherwise it invokes a supplier and returns
// a result of that invocation with non-nil error.
func (o Uint16) OrElseGetErr(supplier func() uint16) (result uint16, err error) {
	if !o.Present {
		return supplier(), errors.New("value of optional.Uint16 is not present")
	}

	return o.Value, nil
}

// MarshalJSON marshals Uint16 to json.
func (o Uint16) MarshalJSON() ([]byte, error) {
	if !o.Present {
		return []byte("null"), nil
	}

	return json.Marshal(o.Value)
}

// UnmarshalJSON unmarshals Uint16 from json.
func (o *Uint16) UnmarshalJSON(data []byte) error {
	if len(data) == 4 && string(data) == "null" {
		return nil
	}

	o.Present = true

	return json.Unmarshal(data, &o.Value)
}
