// Code generated by github.com/eqld/optional/cmd, DO NOT EDIT
package optional

import "encoding/json"

// Uintptr is a superset of type uintptr that has explicit "empty" value.
type Uintptr struct {
	Value   uintptr
	Present bool
}

// MakeUintptr converts uintptr to Uintptr
func MakeUintptr(value uintptr) Uintptr {
	return Uintptr{Value: value, Present: true}
}

// MarshalJSON marshals Uintptr to json
func (o Uintptr) MarshalJSON() ([]byte, error) {
	if !o.Present {
		return []byte("null"), nil
	}

	return json.Marshal(o.Value)
}

// UnmarshalJSON unmarshals Uintptr from json
func (o *Uintptr) UnmarshalJSON(data []byte) error {
	if len(data) == 4 && string(data) == "null" {
		return nil
	}

	o.Present = true

	return json.Unmarshal(data, &o.Value)
}
