package optional

// Code generated by github.com/eqld/optional/cmd, DO NOT EDIT

import (
	"encoding/json"
	"errors"
)

// Uint is a superset of type uint that has explicit "empty" value.
type Uint struct {
	Value   uint
	Present bool
}

// MakeUint converts uint to Uint.
func MakeUint(value uint) Uint {
	return Uint{Value: value, Present: true}
}

// MakeUintFromPtr converts a pointer to uint to Uint.
func MakeUintFromPtr(ptr *uint) Uint {
	if ptr == nil {
		return Uint{}
	}

	return MakeUint(*ptr)
}

// SafeValue safely converts Uint to uint returning its default value if the value of Uint is not present.
func (o Uint) SafeValue() (value uint) {
	if o.Present {
		value = o.Value
	}

	return
}

// SafePtr safely converts Uint to a pointer to uint returning nil pointer if the value of Uint is not present;
// the pointer, if not nil, DOES NOT point to the underlying value of Uint.
func (o Uint) SafePtr() (ptr *uint) {
	if o.Present {
		ptr = new(uint)
		*ptr = o.Value
	}

	return
}

// SafeValueWithFlag safely converts Uint to uint returning it with a flag set to true
// or its default value and the flag set to false if the value of Uint is not present.
func (o Uint) SafeValueWithFlag() (value uint, ok bool) {
	if !o.Present {
		return
	}

	return o.Value, o.Present
}

// SafeValueWithErr safely converts Uint to uint returning it with nil error
// or its default value and non-nil error if the value of Uint is not present.
func (o Uint) SafeValueWithErr() (value uint, err error) {
	if !o.Present {
		err = errors.New("value of optional.Uint is not present")
		return
	}

	return o.Value, nil
}

// SafePtrWithFlag safely converts Uint to a pointer to uint returning a pointer to a value with a flag set to true
// or nil pointer and the flag set to false if the value of Uint is not present;
// the pointer, if not nil, DOES NOT point to the underlying value of Uint.
func (o Uint) SafePtrWithFlag() (ptr *uint, ok bool) {
	if !o.Present {
		return
	}

	ptr = new(uint)
	*ptr, ok = o.Value, o.Present

	return
}

// SafePtrWithErr safely converts Uint to a pointer to uint returning a pointer to a value with nil error
// or nil pointer and non-nil error if the value of Uint is not present;
// the pointer, if not nil, DOES NOT point to the underlying value of Uint.
func (o Uint) SafePtrWithErr() (ptr *uint, err error) {
	if !o.Present {
		err = errors.New("value of optional.Uint is not present")
		return
	}

	ptr = new(uint)
	*ptr = o.Value

	return
}

// Equals returns true if both values are not present or both values are present and are equal according to a provided determinant.
func (o Uint) Equals(other Uint, determinant func(this, other uint) bool) bool {
	return (!o.Present && !other.Present) || (o.Present && other.Present && determinant(o.Value, other.Value))
}

// Compare returns a result of provided comparator and true if both values are present, otherwise it returns 0 and false.
func (o Uint) Compare(other Uint, comparator func(this, other uint) int) (int, bool) {
	if !o.Present || !other.Present {
		return 0, false
	}

	return comparator(o.Value, other.Value), true
}

// Filter returns the Uint if its value is present and it matches the given predicate, otherwise it returns an empty Uint.
func (o Uint) Filter(test func(value uint) bool) (result Uint) {
	if !o.Present || !test(o.Value) {
		return
	}

	return o
}

// Map applies the provided mapping function to a value and returns its result as Uint if the value is present,
// otherwise is returns an empty Uint.
func (o Uint) Map(mapper func(value uint) (result uint, present bool)) (result Uint) {
	if !o.Present {
		return
	}

	result.Value, result.Present = mapper(o.Value)

	return
}

// IfPresent invokes the specified action with the value if it is present.
func (o Uint) IfPresent(action func(value uint)) {
	if o.Present {
		action(o.Value)
	}
}

// OrElse returns the value if it is present, otherwise it returns given other value.
func (o Uint) OrElse(other uint) uint {
	if !o.Present {
		return other
	}

	return o.Value
}

// OrElseWithFlag returns the value if it is present with a flag set to true, otherwise it returns given other value
// and the flag set to false.
func (o Uint) OrElseWithFlag(other uint) (uint, bool) {
	if !o.Present {
		return other, false
	}

	return o.Value, o.Present
}

// OrElseWithErr returns the value if it is present with nil error, otherwise it returns given other value
// and non-nil error.
func (o Uint) OrElseWithErr(other uint) (uint, error) {
	if !o.Present {
		return other, errors.New("value of optional.Uint is not present")
	}

	return o.Value, nil
}

// OrElseGet returns the value if it is present, otherwise it invokes a supplier and returns a result of that invocation.
func (o Uint) OrElseGet(supplier func() uint) uint {
	if !o.Present {
		return supplier()
	}

	return o.Value
}

// OrElseGetWithFlag returns the value if it is present with a flag set to true, otherwise it invokes a supplier and returns
// a result of that invocation with a flag set to false.
func (o Uint) OrElseGetWithFlag(supplier func() uint) (result uint, ok bool) {
	if !o.Present {
		return supplier(), false
	}

	return o.Value, o.Present
}

// OrElseGetWithErr returns the value if it is present with nil error, otherwise it invokes a supplier and returns
// a result of that invocation with non-nil error.
func (o Uint) OrElseGetWithErr(supplier func() uint) (result uint, err error) {
	if !o.Present {
		return supplier(), errors.New("value of optional.Uint is not present")
	}

	return o.Value, nil
}

// OrElseErr returns the value if it is present with nil error, otherwise it invokes an error supplier and returns
// default value and an error returned by the error supplier.
func (o Uint) OrElseErr(errSupplier func() error) (result uint, err error) {
	if !o.Present {
		err = errSupplier()
		return
	}

	return o.Value, nil
}

// MarshalJSON marshals Uint to json.
func (o Uint) MarshalJSON() ([]byte, error) {
	if !o.Present {
		return []byte("null"), nil
	}

	return json.Marshal(o.Value)
}

// UnmarshalJSON unmarshals Uint from json.
func (o *Uint) UnmarshalJSON(data []byte) error {
	if len(data) == 4 && string(data) == "null" {
		return nil
	}

	o.Present = true

	return json.Unmarshal(data, &o.Value)
}
