// Code generated by github.com/eqld/optional/cmd, DO NOT EDIT
package optional

import "encoding/json"

// Int32 is a superset of type int32 that has explicit "empty" value.
type Int32 struct {
	Value   int32
	Present bool
}

// MarshalJSON marshalls Int32 to json
func (o Int32) MarshalJSON() ([]byte, error) {
	if !o.Present {
		return []byte("null"), nil
	}
	return json.Marshal(o.Value)
}

// UnmarshalJSON unmarshalls Int32 from json
func (o *Int32) UnmarshalJSON(data []byte) error {
	if len(data) == 4 && string(data) == "null" {
		return nil
	}

	o.Present = true

	return json.Unmarshal(data, &o.Value)
}
