// Code generated by github.com/eqld/optional/cmd, DO NOT EDIT
package optional

import "encoding/json"

// Int16 is a superset of type int16 that has explicit "empty" value.
type Int16 struct {
	Value   int16
	Present bool
}

// MarshalJSON marshalls Int16 to json
func (o Int16) MarshalJSON() ([]byte, error) {
	if !o.Present {
		return []byte("null"), nil
	}
	return json.Marshal(o.Value)
}

// UnmarshalJSON unmarshalls Int16 from json
func (o *Int16) UnmarshalJSON(data []byte) error {
	if len(data) == 4 && string(data) == "null" {
		return nil
	}

	o.Present = true

	return json.Unmarshal(data, &o.Value)
}
