// Code generated by github.com/eqld/optional/cmd, DO NOT EDIT
package optional

import "encoding/json"

// Float64 is a superset of type float64 that has explicit "empty" value.
type Float64 struct {
	Value   float64
	Present bool
}

// MakeFloat64 converts float64 to Float64
func MakeFloat64(value float64) Float64 {
	return Float64{Value: value, Present: true}
}

// MarshalJSON marshals Float64 to json
func (o Float64) MarshalJSON() ([]byte, error) {
	if !o.Present {
		return []byte("null"), nil
	}

	return json.Marshal(o.Value)
}

// UnmarshalJSON unmarshals Float64 from json
func (o *Float64) UnmarshalJSON(data []byte) error {
	if len(data) == 4 && string(data) == "null" {
		return nil
	}

	o.Present = true

	return json.Unmarshal(data, &o.Value)
}
