package optional

// Code generated by github.com/eqld/optional/cmd, DO NOT EDIT

import (
	"encoding/json"
	"errors"
)

// Uint32 is a superset of type uint32 that has explicit "empty" value.
type Uint32 struct {
	Value   uint32
	Present bool
}

// MakeUint32 converts uint32 to Uint32.
func MakeUint32(value uint32) Uint32 {
	return Uint32{Value: value, Present: true}
}

// MakeUint32FromPtr converts a pointer to uint32 to Uint32.
func MakeUint32FromPtr(ptr *uint32) Uint32 {
	if ptr == nil {
		return Uint32{}
	}

	return MakeUint32(*ptr)
}

// SafeValue safely converts Uint32 to uint32 returning its default value if the value of Uint32 is not present.
func (o Uint32) SafeValue() (value uint32) {
	if o.Present {
		value = o.Value
	}

	return
}

// SafePtr safely converts Uint32 to a pointer to uint32 returning nil pointer if the value of Uint32 is not present;
// the pointer, if not nil, DOES NOT point to the underlying value of Uint32.
func (o Uint32) SafePtr() (ptr *uint32) {
	if o.Present {
		ptr = new(uint32)
		*ptr = o.Value
	}

	return
}

// SafeValueWithFlag safely converts Uint32 to uint32 returning it with a flag set to true
// or its default value and the flag set to false if the value of Uint32 is not present.
func (o Uint32) SafeValueWithFlag() (value uint32, ok bool) {
	if !o.Present {
		return
	}

	return o.Value, o.Present
}

// SafeValueWithErr safely converts Uint32 to uint32 returning it with nil error
// or its default value and non-nil error if the value of Uint32 is not present.
func (o Uint32) SafeValueWithErr() (value uint32, err error) {
	if !o.Present {
		err = errors.New("value of optional.Uint32 is not present")
		return
	}

	return o.Value, nil
}

// SafePtrWithFlag safely converts Uint32 to a pointer to uint32 returning a pointer to a value with a flag set to true
// or nil pointer and the flag set to false if the value of Uint32 is not present;
// the pointer, if not nil, DOES NOT point to the underlying value of Uint32.
func (o Uint32) SafePtrWithFlag() (ptr *uint32, ok bool) {
	if !o.Present {
		return
	}

	ptr = new(uint32)
	*ptr, ok = o.Value, o.Present

	return
}

// SafePtrWithErr safely converts Uint32 to a pointer to uint32 returning a pointer to a value with nil error
// or nil pointer and non-nil error if the value of Uint32 is not present;
// the pointer, if not nil, DOES NOT point to the underlying value of Uint32.
func (o Uint32) SafePtrWithErr() (ptr *uint32, err error) {
	if !o.Present {
		err = errors.New("value of optional.Uint32 is not present")
		return
	}

	ptr = new(uint32)
	*ptr = o.Value

	return
}

// MarshalJSON marshals Uint32 to json.
func (o Uint32) MarshalJSON() ([]byte, error) {
	if !o.Present {
		return []byte("null"), nil
	}

	return json.Marshal(o.Value)
}

// UnmarshalJSON unmarshals Uint32 from json.
func (o *Uint32) UnmarshalJSON(data []byte) error {
	if len(data) == 4 && string(data) == "null" {
		return nil
	}

	o.Present = true

	return json.Unmarshal(data, &o.Value)
}
