// Code generated by github.com/eqld/optional/cmd, DO NOT EDIT
package optional

import "encoding/json"

// Int32 is a superset of type int32 that has explicit "empty" value.
type Int32 struct {
	Value   int32
	Present bool
}

// MakeInt32 converts int32 to Int32
func MakeInt32(value int32) Int32 {
	return Int32{Value: value, Present: true}
}

// MarshalJSON marshals Int32 to json
func (o Int32) MarshalJSON() ([]byte, error) {
	if !o.Present {
		return []byte("null"), nil
	}

	return json.Marshal(o.Value)
}

// UnmarshalJSON unmarshals Int32 from json
func (o *Int32) UnmarshalJSON(data []byte) error {
	if len(data) == 4 && string(data) == "null" {
		return nil
	}

	o.Present = true

	return json.Unmarshal(data, &o.Value)
}
