package optional

// Code generated by github.com/eqld/optional/cmd, DO NOT EDIT

import (
	"encoding/json"
	"errors"
)

// Int8 is a superset of type int8 that has explicit "empty" value.
type Int8 struct {
	Value   int8
	Present bool
}

// MakeInt8 converts int8 to Int8.
func MakeInt8(value int8) Int8 {
	return Int8{Value: value, Present: true}
}

// MakeInt8FromPtr converts a pointer to int8 to Int8.
func MakeInt8FromPtr(ptr *int8) Int8 {
	if ptr == nil {
		return Int8{}
	}

	return MakeInt8(*ptr)
}

// SafeValue safely converts Int8 to int8 returning its default value if the value of Int8 is not present.
func (o Int8) SafeValue() (value int8) {
	if o.Present {
		value = o.Value
	}

	return
}

// SafePtr safely converts Int8 to a pointer to int8 returning nil pointer if the value of Int8 is not present;
// the pointer, if not nil, DOES NOT point to the underlying value of Int8.
func (o Int8) SafePtr() (ptr *int8) {
	if o.Present {
		ptr = new(int8)
		*ptr = o.Value
	}

	return
}

// SafeValueWithFlag safely converts Int8 to int8 returning it with a flag set to true
// or its default value and the flag set to false if the value of Int8 is not present.
func (o Int8) SafeValueWithFlag() (value int8, ok bool) {
	if !o.Present {
		return
	}

	return o.Value, o.Present
}

// SafeValueWithErr safely converts Int8 to int8 returning it with nil error
// or its default value and non-nil error if the value of Int8 is not present.
func (o Int8) SafeValueWithErr() (value int8, err error) {
	if !o.Present {
		err = errors.New("value of optional.Int8 is not present")
		return
	}

	return o.Value, nil
}

// SafePtrWithFlag safely converts Int8 to a pointer to int8 returning a pointer to a value with a flag set to true
// or nil pointer and the flag set to false if the value of Int8 is not present;
// the pointer, if not nil, DOES NOT point to the underlying value of Int8.
func (o Int8) SafePtrWithFlag() (ptr *int8, ok bool) {
	if !o.Present {
		return
	}

	ptr = new(int8)
	*ptr, ok = o.Value, o.Present

	return
}

// SafePtrWithErr safely converts Int8 to a pointer to int8 returning a pointer to a value with nil error
// or nil pointer and non-nil error if the value of Int8 is not present;
// the pointer, if not nil, DOES NOT point to the underlying value of Int8.
func (o Int8) SafePtrWithErr() (ptr *int8, err error) {
	if !o.Present {
		err = errors.New("value of optional.Int8 is not present")
		return
	}

	ptr = new(int8)
	*ptr = o.Value

	return
}

// MarshalJSON marshals Int8 to json.
func (o Int8) MarshalJSON() ([]byte, error) {
	if !o.Present {
		return []byte("null"), nil
	}

	return json.Marshal(o.Value)
}

// UnmarshalJSON unmarshals Int8 from json.
func (o *Int8) UnmarshalJSON(data []byte) error {
	if len(data) == 4 && string(data) == "null" {
		return nil
	}

	o.Present = true

	return json.Unmarshal(data, &o.Value)
}
