// Code generated by github.com/eqld/optional/cmd, DO NOT EDIT
package optional

import "encoding/json"

// Rune is a superset of type rune that has explicit "empty" value.
type Rune struct {
	Value   rune
	Present bool
}

// MakeRune converts rune to Rune
func MakeRune(value rune) Rune {
	return Rune{Value: value, Present: true}
}

// MarshalJSON marshals Rune to json
func (o Rune) MarshalJSON() ([]byte, error) {
	if !o.Present {
		return []byte("null"), nil
	}

	return json.Marshal(o.Value)
}

// UnmarshalJSON unmarshals Rune from json
func (o *Rune) UnmarshalJSON(data []byte) error {
	if len(data) == 4 && string(data) == "null" {
		return nil
	}

	o.Present = true

	return json.Unmarshal(data, &o.Value)
}
