// Code generated by github.com/eqld/optional/cmd, DO NOT EDIT
package optional

import "encoding/json"

// Complex128 is a superset of type complex128 that has explicit "empty" value.
type Complex128 struct {
	Value   complex128
	Present bool
}

// MakeComplex128 converts complex128 to Complex128
func MakeComplex128(value complex128) Complex128 {
	return Complex128{Value: value, Present: true}
}

// MarshalJSON marshals Complex128 to json
func (o Complex128) MarshalJSON() ([]byte, error) {
	if !o.Present {
		return []byte("null"), nil
	}

	return json.Marshal(o.Value)
}

// UnmarshalJSON unmarshals Complex128 from json
func (o *Complex128) UnmarshalJSON(data []byte) error {
	if len(data) == 4 && string(data) == "null" {
		return nil
	}

	o.Present = true

	return json.Unmarshal(data, &o.Value)
}
