package optional

// Code generated by github.com/eqld/optional/cmd, DO NOT EDIT

import (
	"encoding/json"
	"errors"
)

// Complex128 is a superset of type complex128 that has explicit "empty" value.
type Complex128 struct {
	Value   complex128
	Present bool
}

// MakeComplex128 converts complex128 to Complex128.
func MakeComplex128(value complex128) Complex128 {
	return Complex128{Value: value, Present: true}
}

// MakeComplex128FromPtr converts a pointer to complex128 to Complex128.
func MakeComplex128FromPtr(ptr *complex128) Complex128 {
	if ptr == nil {
		return Complex128{}
	}

	return MakeComplex128(*ptr)
}

// SafeValue safely converts Complex128 to complex128 returning its default value if the value of Complex128 is not present.
func (o Complex128) SafeValue() (value complex128) {
	if o.Present {
		value = o.Value
	}

	return
}

// SafePtr safely converts Complex128 to a pointer to complex128 returning nil pointer if the value of Complex128 is not present;
// the pointer, if not nil, DOES NOT point to the underlying value of Complex128.
func (o Complex128) SafePtr() (ptr *complex128) {
	if o.Present {
		ptr = new(complex128)
		*ptr = o.Value
	}

	return
}

// SafeValueWithFlag safely converts Complex128 to complex128 returning it with a flag set to true
// or its default value and the flag set to false if the value of Complex128 is not present.
func (o Complex128) SafeValueWithFlag() (value complex128, ok bool) {
	if !o.Present {
		return
	}

	return o.Value, o.Present
}

// SafeValueWithErr safely converts Complex128 to complex128 returning it with nil error
// or its default value and non-nil error if the value of Complex128 is not present.
func (o Complex128) SafeValueWithErr() (value complex128, err error) {
	if !o.Present {
		err = errors.New("value of optional.Complex128 is not present")
		return
	}

	return o.Value, nil
}

// SafePtrWithFlag safely converts Complex128 to a pointer to complex128 returning a pointer to a value with a flag set to true
// or nil pointer and the flag set to false if the value of Complex128 is not present;
// the pointer, if not nil, DOES NOT point to the underlying value of Complex128.
func (o Complex128) SafePtrWithFlag() (ptr *complex128, ok bool) {
	if !o.Present {
		return
	}

	ptr = new(complex128)
	*ptr, ok = o.Value, o.Present

	return
}

// SafePtrWithErr safely converts Complex128 to a pointer to complex128 returning a pointer to a value with nil error
// or nil pointer and non-nil error if the value of Complex128 is not present;
// the pointer, if not nil, DOES NOT point to the underlying value of Complex128.
func (o Complex128) SafePtrWithErr() (ptr *complex128, err error) {
	if !o.Present {
		err = errors.New("value of optional.Complex128 is not present")
		return
	}

	ptr = new(complex128)
	*ptr = o.Value

	return
}

// Equals returns true if both values are not present or both values are present and are equal according to a provided determinant.
func (o Complex128) Equals(other Complex128, determinant func(this, other complex128) bool) bool {
	return (!o.Present && !other.Present) || (o.Present && other.Present && determinant(o.Value, other.Value))
}

// Compare returns a result of provided comparator and true if both values are present, otherwise it returns 0 and false.
func (o Complex128) Compare(other Complex128, comparator func(this, other complex128) int) (int, bool) {
	if !o.Present || !other.Present {
		return 0, false
	}

	return comparator(o.Value, other.Value), true
}

// Filter returns the Complex128 if its value is present and it matches the given predicate, otherwise it returns an empty Complex128.
func (o Complex128) Filter(test func(value complex128) bool) (result Complex128) {
	if !o.Present || !test(o.Value) {
		return
	}

	return o
}

// Map applies the provided mapping function to a value and returns its result as Complex128 if the value is present,
// otherwise is returns an empty Complex128.
func (o Complex128) Map(mapper func(value complex128) (result complex128, present bool)) (result Complex128) {
	if !o.Present {
		return
	}

	result.Value, result.Present = mapper(o.Value)

	return
}

// IfPresent invokes the specified action with the value if it is present.
func (o Complex128) IfPresent(action func(value complex128)) {
	if o.Present {
		action(o.Value)
	}
}

// OrElse returns the value if it is present, otherwise it returns given other value.
func (o Complex128) OrElse(other complex128) complex128 {
	if !o.Present {
		return other
	}

	return o.Value
}

// OrElseWithFlag returns the value if it is present with a flag set to true, otherwise it returns given other value
// and the flag set to false.
func (o Complex128) OrElseWithFlag(other complex128) (complex128, bool) {
	if !o.Present {
		return other, false
	}

	return o.Value, o.Present
}

// OrElseWithErr returns the value if it is present with nil error, otherwise it returns given other value
// and non-nil error.
func (o Complex128) OrElseWithErr(other complex128) (complex128, error) {
	if !o.Present {
		return other, errors.New("value of optional.Complex128 is not present")
	}

	return o.Value, nil
}

// OrElseGet returns the value if it is present, otherwise it invokes a supplier and returns a result of that invocation.
func (o Complex128) OrElseGet(supplier func() complex128) complex128 {
	if !o.Present {
		return supplier()
	}

	return o.Value
}

// OrElseGetWithFlag returns the value if it is present with a flag set to true, otherwise it invokes a supplier and returns
// a result of that invocation with a flag set to false.
func (o Complex128) OrElseGetWithFlag(supplier func() complex128) (result complex128, ok bool) {
	if !o.Present {
		return supplier(), false
	}

	return o.Value, o.Present
}

// OrElseGetWithErr returns the value if it is present with nil error, otherwise it invokes a supplier and returns
// a result of that invocation with non-nil error.
func (o Complex128) OrElseGetWithErr(supplier func() complex128) (result complex128, err error) {
	if !o.Present {
		return supplier(), errors.New("value of optional.Complex128 is not present")
	}

	return o.Value, nil
}

// OrElseErr returns the value if it is present with nil error, otherwise it invokes an error supplier and returns
// default value and an error returned by the error supplier.
func (o Complex128) OrElseErr(errSupplier func() error) (result complex128, err error) {
	if !o.Present {
		err = errSupplier()
		return
	}

	return o.Value, nil
}

// MarshalJSON marshals Complex128 to json.
func (o Complex128) MarshalJSON() ([]byte, error) {
	if !o.Present {
		return []byte("null"), nil
	}

	return json.Marshal(o.Value)
}

// UnmarshalJSON unmarshals Complex128 from json.
func (o *Complex128) UnmarshalJSON(data []byte) error {
	if len(data) == 4 && string(data) == "null" {
		return nil
	}

	o.Present = true

	return json.Unmarshal(data, &o.Value)
}
