package optional

// Code generated by github.com/eqld/optional/cmd, DO NOT EDIT

import (
	"encoding/json"
	"errors"
)

// Uint8 is a superset of type uint8 that has explicit "empty" value.
type Uint8 struct {
	Value   uint8
	Present bool
}

// MakeUint8 converts uint8 to Uint8.
func MakeUint8(value uint8) Uint8 {
	return Uint8{Value: value, Present: true}
}

// MakeUint8FromPtr converts a pointer to uint8 to Uint8.
func MakeUint8FromPtr(ptr *uint8) Uint8 {
	if ptr == nil {
		return Uint8{}
	}

	return MakeUint8(*ptr)
}

// SafeValue safely converts Uint8 to uint8 returning its default value if the value of Uint8 is not present.
func (o Uint8) SafeValue() (value uint8) {
	if o.Present {
		value = o.Value
	}

	return
}

// SafePtr safely converts Uint8 to a pointer to uint8 returning nil pointer if the value of Uint8 is not present;
// the pointer, if not nil, DOES NOT point to the underlying value of Uint8.
func (o Uint8) SafePtr() (ptr *uint8) {
	if o.Present {
		ptr = new(uint8)
		*ptr = o.Value
	}

	return
}

// SafeValueWithFlag safely converts Uint8 to uint8 returning it with a flag set to true
// or its default value and the flag set to false if the value of Uint8 is not present.
func (o Uint8) SafeValueWithFlag() (value uint8, ok bool) {
	if !o.Present {
		return
	}

	return o.Value, o.Present
}

// SafeValueWithErr safely converts Uint8 to uint8 returning it with nil error
// or its default value and non-nil error if the value of Uint8 is not present.
func (o Uint8) SafeValueWithErr() (value uint8, err error) {
	if !o.Present {
		err = errors.New("value of optional.Uint8 is not present")
		return
	}

	return o.Value, nil
}

// SafePtrWithFlag safely converts Uint8 to a pointer to uint8 returning a pointer to a value with a flag set to true
// or nil pointer and the flag set to false if the value of Uint8 is not present;
// the pointer, if not nil, DOES NOT point to the underlying value of Uint8.
func (o Uint8) SafePtrWithFlag() (ptr *uint8, ok bool) {
	if !o.Present {
		return
	}

	ptr = new(uint8)
	*ptr, ok = o.Value, o.Present

	return
}

// SafePtrWithErr safely converts Uint8 to a pointer to uint8 returning a pointer to a value with nil error
// or nil pointer and non-nil error if the value of Uint8 is not present;
// the pointer, if not nil, DOES NOT point to the underlying value of Uint8.
func (o Uint8) SafePtrWithErr() (ptr *uint8, err error) {
	if !o.Present {
		err = errors.New("value of optional.Uint8 is not present")
		return
	}

	ptr = new(uint8)
	*ptr = o.Value

	return
}

// Equals returns true if both values are not present or both values are present and are equal according to a provided determinant.
func (o Uint8) Equals(other Uint8, determinant func(this, other uint8) bool) bool {
	return (!o.Present && !other.Present) || (o.Present && other.Present && determinant(o.Value, other.Value))
}

// Compare returns a result of provided comparator and true if both values are present, otherwise it returns 0 and false.
func (o Uint8) Compare(other Uint8, comparator func(this, other uint8) int) (int, bool) {
	if !o.Present || !other.Present {
		return 0, false
	}

	return comparator(o.Value, other.Value), true
}

// Filter returns the Uint8 if its value is present and it matches the given predicate, otherwise it returns an empty Uint8.
func (o Uint8) Filter(test func(value uint8) bool) (result Uint8) {
	if !o.Present || !test(o.Value) {
		return
	}

	return o
}

// Map applies the provided mapping function to a value and returns its result as Uint8 if the value is present,
// otherwise is returns an empty Uint8.
func (o Uint8) Map(mapper func(value uint8) (result uint8, present bool)) (result Uint8) {
	if !o.Present {
		return
	}

	result.Value, result.Present = mapper(o.Value)

	return
}

// IfPresent invokes the specified action with the value if it is present.
func (o Uint8) IfPresent(action func(value uint8)) {
	if o.Present {
		action(o.Value)
	}
}

// OrElse returns the value if it is present, otherwise it returns given other value.
func (o Uint8) OrElse(other uint8) uint8 {
	if !o.Present {
		return other
	}

	return o.Value
}

// OrElseWithFlag returns the value if it is present with a flag set to true, otherwise it returns given other value
// and the flag set to false.
func (o Uint8) OrElseWithFlag(other uint8) (uint8, bool) {
	if !o.Present {
		return other, false
	}

	return o.Value, o.Present
}

// OrElseWithErr returns the value if it is present with nil error, otherwise it returns given other value
// and non-nil error.
func (o Uint8) OrElseWithErr(other uint8) (uint8, error) {
	if !o.Present {
		return other, errors.New("value of optional.Uint8 is not present")
	}

	return o.Value, nil
}

// OrElseGet returns the value if it is present, otherwise it invokes a supplier and returns a result of that invocation.
func (o Uint8) OrElseGet(supplier func() uint8) uint8 {
	if !o.Present {
		return supplier()
	}

	return o.Value
}

// OrElseGetWithFlag returns the value if it is present with a flag set to true, otherwise it invokes a supplier and returns
// a result of that invocation with a flag set to false.
func (o Uint8) OrElseGetWithFlag(supplier func() uint8) (result uint8, ok bool) {
	if !o.Present {
		return supplier(), false
	}

	return o.Value, o.Present
}

// OrElseGetWithErr returns the value if it is present with nil error, otherwise it invokes a supplier and returns
// a result of that invocation with non-nil error.
func (o Uint8) OrElseGetWithErr(supplier func() uint8) (result uint8, err error) {
	if !o.Present {
		return supplier(), errors.New("value of optional.Uint8 is not present")
	}

	return o.Value, nil
}

// OrElseErr returns the value if it is present with nil error, otherwise it invokes an error supplier and returns
// default value and an error returned by the error supplier.
func (o Uint8) OrElseErr(errSupplier func() error) (result uint8, err error) {
	if !o.Present {
		err = errSupplier()
		return
	}

	return o.Value, nil
}

// MarshalJSON marshals Uint8 to json.
func (o Uint8) MarshalJSON() ([]byte, error) {
	if !o.Present {
		return []byte("null"), nil
	}

	return json.Marshal(o.Value)
}

// UnmarshalJSON unmarshals Uint8 from json.
func (o *Uint8) UnmarshalJSON(data []byte) error {
	if len(data) == 4 && string(data) == "null" {
		return nil
	}

	o.Present = true

	return json.Unmarshal(data, &o.Value)
}
