// Code generated by github.com/eqld/optional/cmd, DO NOT EDIT
package optional

import "encoding/json"

// String is a superset of type string that has explicit "empty" value.
type String struct {
	Value   string
	Present bool
}

// MakeString converts string to String
func MakeString(value string) String {
	return String{Value: value, Present: true}
}

// MarshalJSON marshals String to json
func (o String) MarshalJSON() ([]byte, error) {
	if !o.Present {
		return []byte("null"), nil
	}

	return json.Marshal(o.Value)
}

// UnmarshalJSON unmarshals String from json
func (o *String) UnmarshalJSON(data []byte) error {
	if len(data) == 4 && string(data) == "null" {
		return nil
	}

	o.Present = true

	return json.Unmarshal(data, &o.Value)
}
