package main

const template = `// Code generated by github.com/eqld/optional/cmd, DO NOT EDIT
package _P_

import "encoding/json"

// _TO_ is a superset of type _T_ that has explicit "empty" value.
type _TO_ struct {
	Value   _T_
	Present bool
}

// MarshalJSON marshalls _TO_ to json
func (o _TO_) MarshalJSON() ([]byte, error) {
	if !o.Present {
		return []byte("null"), nil
	}
	return json.Marshal(o.Value)
}

// UnmarshalJSON unmarshalls _TO_ from json
func (o *_TO_) UnmarshalJSON(data []byte) error {
	if len(data) == 4 && string(data) == "null" {
		return nil
	}

	o.Present = true

	return json.Unmarshal(data, &o.Value)
}
`
